-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: 17478a0a50faf20fd8e5b3fefe7435cea410df0b
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: flake8
